# Generated by Django 3.2.6 on 2021-08-28 05:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_basic', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Aiticle',
            new_name='Article',
        ),
    ]
